-- FUNCIONES DE AGREGACIÓN

-- COUNT
SELECT COUNT(*) FROM BOOKS;
SELECT COUNT(AUTHOR_FNAME) FROM BOOKS; -- CUENTA FILAS, INCLUYE NULLS
SELECT COUNT(DISTINCT AUTHOR_FNAME) FROM BOOKS;
SELECT COUNT(DISTINCT RELEASED_YEAR) FROM BOOKS;

-- CUANTOS TITULOS CONIENEN LA PALABRA THE
SELECT TITLE FROM BOOKS WHERE TITLE LIKE "%THE%";
SELECT COUNT(TITLE) FROM BOOKS WHERE TITLE LIKE "%THE%";

-- GROUP BY
SELECT AUTHOR_LNAME FROM BOOKS;
SELECT AUTHOR_LNAME FROM BOOKS GROUP BY AUTHOR_LNAME;
SELECT AUTHOR_LNAME, COUNT(*) AS BOOKS_WRITTEN FROM BOOKS GROUP BY AUTHOR_LNAME;
SELECT AUTHOR_LNAME, COUNT(*) AS BOOKS_WRITTEN FROM BOOKS GROUP BY AUTHOR_LNAME ORDER BY BOOKS_WRITTEN;

SELECT RELEASED_YEAR, COUNT(*) FROM BOOKS GROUP BY RELEASED_YEAR;

-- MIN MAX
SELECT MIN(PAGES) FROM BOOKS; 
SELECT MAX(PAGES) FROM BOOKS;
SELECT MIN(RELEASED_YEAR) FROM BOOKS; -- PRIMER AÑO DE PUBLICACION
SELECT MAX(RELEASED_YEAR) FROM BOOKS; -- ULTIMO AÑO DE PUBLICACION

SELECT MIN(RELEASED_YEAR), MAX(PAGES) FROM BOOKS;

-- SUBQUERIES: CUAL ES EL LIBRO QUE TIENE MAS PAGINAS
SELECT * FROM BOOKS 
WHERE PAGES = (SELECT MAX(PAGES) FROM BOOKS);

SELECT TITLE FROM BOOKS 
WHERE RELEASED_YEAR = (SELECT MIN(RELEASED_YEAR) FROM BOOKS);

-- AGRUPAR POR MULTIPLES COLUMNAS
SELECT AUTHOR_LNAME, COUNT(*) FROM BOOKS GROUP BY AUTHOR_LNAME;
SELECT AUTHOR_LNAME, COUNT(*) FROM BOOKS GROUP BY AUTHOR_LNAME, AUTHOR_FNAME;
SELECT AUTHOR_LNAME, AUTHOR_FNAME, COUNT(*) FROM BOOKS GROUP BY AUTHOR_LNAME, AUTHOR_FNAME;

-- MIN MAX CON GROUP BYENCUENTRA EL AÑO EN EL QUE CADA AUTOR PUBLICO SU PRIMER LIBRO
SELECT AUTHOR_LNAME, AUTHOR_FNAME, MIN(RELEASED_YEAR)
FROM BOOKS
GROUP BY AUTHOR_LNAME, AUTHOR_FNAME;

SELECT AUTHOR_LNAME, AUTHOR_FNAME, MIN(RELEASED_YEAR), MAX(RELEASED_YEAR)
FROM BOOKS
GROUP BY AUTHOR_LNAME, AUTHOR_FNAME;

SELECT AUTHOR_LNAME, AUTHOR_FNAME, MIN(RELEASED_YEAR), MAX(RELEASED_YEAR), COUNT(*) AS NUM
FROM BOOKS
GROUP BY AUTHOR_LNAME, AUTHOR_FNAME
ORDER BY MIN(RELEASED_YEAR) - MAX(RELEASED_YEAR);

-- ENCONTRAR EL LIBRO CON MAYOR NUMERO DE PAGINAS POR AUTOR

-- SUM: SUMA
SELECT SUM(PAGES) FROM BOOKS;
SELECT AUTHOR_LNAME, SUM(PAGES) FROM BOOKS GROUP BY AUTHOR_LNAME;

-- PROMEDIO AVG
SELECT AVG(RELEASED_YEAR) FROM BOOKS;
SELECT AVG(PAGES) FROM BOOKS;

SELECT RELEASED_YEAR, AVG(STOCK_QUANTITY) FROM BOOKS GROUP BY RELEASED_YEAR;

-- EJERCICIOS
-- MOSTRAR EL NUMERO TOTAL DE LIBROS EN LA DB
-- CUANTOS LIBROS SE PUBLICARON EN CADA AÑO
-- NUMERO TOTAL DE LIBROS EN STOCK
-- PROMEDIO DEL AÑO DE PUBLICACION POR AUTOR
-- NOMBRE **COMPLETO** DEL AUTOR QUE ESCRIBIO EL LIBRO MAS LARGO
-- UNA BUSQUEDA QUE MUESTRE EL AÑO, LA CANTIDAD DE LIBROS POR AÑO, Y EL PROMERDIO DE PAGINAS PRO AÑO
