--  OTROS TIPOS DE DATOS

-- MOSTRAR LA DOCUMENTACION DE LOS TIPOS DE DATOS PERO NO HACE ENFASIS EN ELLOS. 
-- HACER ENFASIS EN LAS FECHAS

-- FECHAS Y TIEMPO
-- TIPOS:
-- DATE: YYYY-MM-DD
-- TIME: HORA HH:MM:SS
-- DATETIME: YYYY-MM-DD HH:MM:SS

CREATE TABLE PEOPLE (
	name varchar(50),
    birthdate DATE,
    birthtime TIME,
    birthdt DATETIME
);
DESC PEOPLE;
INSERT INTO PEOPLE (NAME, birthdate, birthtime, birthdt) VALUES ("ELTON", "2000-12-25", "11:00:00", "2000-12-25 11:00:00");
INSERT INTO PEOPLE (NAME, birthdate, birthtime, birthdt) VALUES ("LULU", "1985-04-10", "9:45:10", "1985-04-10 9:45:10");
INSERT INTO PEOPLE (NAME, birthdate, birthtime, birthdt) VALUES ("JAVI", "1989-10-26", "13:45:10", "1989-10-26 13:45:10");

SELECT * FROM PEOPLE;


-- CURDATE, CURTIME & NOW
SELECT curdate();
SELECT current_time();
SELECT NOW();

INSERT INTO PEOPLE (NAME, birthdate, birthtime, birthdt) VALUES ("JAVIS SON", CURDATE(), CURTIME(), NOW());

-- FUNCIONES CON FECHAS
SELECT BIRTHDATE FROM PEOPLE;

SELECT DAY(BIRTHDATE), DAYOFWEEK(BIRTHDATE), DAYOFYEAR(BIRTHDATE) FROM PEOPLE;
SELECT MONTHNAME(BIRTHDATE) FROM PEOPLE;
SELECT YEAR(BIRTHDATE) FROM PEOPLE;


SELECT BIRTHDT, HOUR(BIRTHDT), MINUTE(BIRTHDT), second(BIRTHDT) FROM PEOPLE;
SELECT BIRTHDT, DATE(BIRTHDT) FROM PEOPLE;

-- DAR FORMATO A FECHAS
SELECT BIRTHDT, DATE_FORMAT(BIRTHDT, "%b") FROM PEOPLE;
SELECT BIRTHDT, DATE_FORMAT(BIRTHDT, "%a") FROM PEOPLE;
SELECT BIRTHDT, DATE_FORMAT(BIRTHDT, "%D %a-%b") FROM PEOPLE;

-- matematica con fechas
SELECT DATEDIFF(CURDATE(), BIRTHDATE) FROM PEOPLE; -- DEVUELVE DÍAS
SELECT DATE_ADD(NOW(), INTERVAL 1 DAY) FROM PEOPLE; -- DEVUELVE DÍAS
SELECT DATE_ADD(NOW(), INTERVAL 1 YEAR) FROM PEOPLE; -- DEVUELVE DÍAS
SELECT DATE_ADD(NOW(), INTERVAL 1 MONTH) FROM PEOPLE; -- DEVUELVE DÍAS

SELECT TIMEDIFF(CURTIME(), "07:00:00");

SELECT NOW() - INTERVAL 18 YEAR;
SELECT NOW() + INTERVAL 18 YEAR;

-- TIMESTAPS
-- COMBINA UNA FECHA Y UNA HORA, DIFERENCIA ES QUE SON MAS PEQUEÑOS PORQUEN CONTIENEN MENOS FECHAS
-- TIENE UN RANGO MENOR 1970-01-01 HASTA 203801-19
-- SE COMPORTAN IGUAL A DATETIME

-- DEFAULT AND ON UPDATES

USE BOOK_SHOP;

CREATE TABLE post (
	post_text TEXT,
    created_at TIMESTAMP DEFAULT   current_timestamp
);

INSERT INTO POST (POST_TEXT) VALUES ("ABDHBASHD BIBDBABHD");
SELECT * FROM POST;

-- ON UPDATE
CREATE TABLE post2 (
	post_text TEXT,
    created_at TIMESTAMP DEFAULT   current_timestamp,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO POST2 (POST_TEXT) VALUES ("I LOVE LIFE");
SELECT * FROM POST2;

UPDATE POST2 SET POST_TEXT = "I LOVE GOD";
SELECT * FROM POST2;

-- EJERCICIOS 
-- ESCRIBIR UN SELECT QUE MUESTRE LA HORA ACTUAL
-- ESCRIBIR UN SELECT QUE MUESTRE LA FECHA ACTUAL
-- ESCRIBIR UN SELECT QUE MUESTRE EL DIA DE LA SEMANA ACTUAL (NUMERO)
-- ESCRIBIR UN SELECT QUE MUESTRE EL DIA DE LA SEMANA ACTUAL (EL NOMBRE)
-- ESCRIBIR UN SELECT QUE MUESTRE LA FECHA ACTUAL EN FORMATO MM/DD/YYYY
-- ESCRIBIR UN SELECT QUE MUESTRE LA FECHA ACTUAL EN FORMATO JENUARY 2ND AT 3:15











