-- COMPARISON AND LOGICAL OPERATIONS
--  NOS PERMITEN REALIZAR BUSQUEDAS MAS COMLEJAS CON LÓGICA MAS COMPLEJA
USE BOOK_SHOP;
-- NOT EQUAL
SELECT * FROM BOOKS WHERE RELEASED_YEAR = 2017;

SELECT * FROM BOOKS WHERE RELEASED_YEAR != 2017;
SELECT * FROM BOOKS WHERE AUTHOR_LNAME != "GAIMAN";

-- NOT LIKE
SELECT * FROM BOOKS WHERE TITLE LIKE "% %"; -- TODOS LOS LIBROS QUE TIENEN UN ESPACIO EN EL TITULO
SELECT * FROM BOOKS WHERE TITLE NOT LIKE "% %"; -- TODOS LOS LIBROS QUE TIENEN UN ESPACIO EN EL TITULO

SELECT * FROM BOOKS 
WHERE AUTHOR_FNAME LIKE "DA%";

SELECT * FROM BOOKS 
WHERE AUTHOR_FNAME NOT LIKE "DA%";

-- MAYOR QUE, MENOR QUE
SELECT * FROM BOOKS WHERE STOCK_QUANTITY > 100;
SELECT * FROM BOOKS WHERE STOCK_QUANTITY < 100;
SELECT 99 > 1;

-- LOGICAL AND
SELECT * FROM BOOKS WHERE RELEASED_YEAR > 2000 AND PAGES > 300;
SELECT * FROM BOOKS WHERE RELEASED_YEAR > 2000 AND PAGES > 500;

SELECT * FROM BOOKS
WHERE AUTHOR_LNAME="EGGERS" AND
RELEASED_YEAR > 2010 AND
TITLE LIKE "%NOVEL%";

SELECT TITLE, PAGES FROM BOOKS WHERE char_length(TITLE) > 30
AND PAGES > 400
;

-- LOGICAL OR
SELECT * FROM BOOKS WHERE AUTHOR_LNAME = "EGGERS" OR
RELEASED_YEAR > 2010;

-- BETWEEN: EN UN RANGO
-- SELECT LOS BOOKS ENTRE 2004 AND 2015

SELECT * FROM BOOKS WHERE RELEASED_YEAR <= 2015 AND RELEASED_YEAR >=  2004 ORDER BY RELEASED_YEAR;

SELECT * FROM BOOKS WHERE RELEASED_YEAR BETWEEN 2004 AND 2014;

SELECT TITLE, PAGES FROM BOOKS WHERE PAGES BETWEEN 200 AND 300;

-- NO BETWEEN
SELECT TITLE, PAGES FROM BOOKS WHERE PAGES NOT BETWEEN 200 AND 300;

-- COMPARANDO FECHAS
SELECT * FROM PEOPLE WHERE BIRTHDATE < "2005-01-01";
SELECT * FROM PEOPLE WHERE YEAR(BIRTHDATE) < 2005;
SELECT * FROM PEOPLE WHERE HOUR(BIRTHTIME) < 13;

-- EL OPERADOR IN y NOT IN
SELECT * FROM BOOKS
WHERE AUTHOR_LNAME IN ("CARVER", "LAHIRI", "SMITH");

SELECT * FROM BOOKS
WHERE AUTHOR_LNAME NOT IN ("CARVER", "LAHIRI", "SMITH");


SELECT * FROM BOOKS
WHERE RELEASED_YEAR % 2 != 0; -- AÑOS IMPARES

-- IS NULL
-- NO USAR EL = CON EL NULL
SELECT * FROM BOOKS WHERE TITLE IS NULL;
SELECT * FROM BOOKS WHERE TITLE IS NOT NULL;

-- EJERCICIOS
-- TODOS LOS LIBROS ESCRITOS ANTES DE 1980
-- TODOS LIBROS ESCRITOS POR EGGS O CHABON
-- TODOS LOS LIBROS PUBLICADOS POR LAHIRI DESPUES DE 2010
-- TODOS LOS LIBROS CON PAGINAS ENTRE 200 Y 300
-- TODOS LOS LIBROS CUYO AUTHOR_LNAME EMPIEZA CON C o S
-- OTROS EJERCICIOS EN LAS DIAPOSIIVAS


